/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_java_groovy_nativec_NativeCalls */

#ifndef _Included_com_example_java_groovy_nativec_NativeCalls
#define _Included_com_example_java_groovy_nativec_NativeCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_java_groovy_nativec_NativeCalls
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_java_groovy_nativec_NativeCalls_printText__
  (JNIEnv *, jclass);

/*
 * Class:     com_example_java_groovy_nativec_NativeCalls
 * Method:    printText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_java_groovy_nativec_NativeCalls_printText__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
